package com.cars.iivmshome.sysmanage.dao;

import java.util.List;
import java.util.Map;

import com.cars.iivmshome.base.vo.BaseCountsVo;
import com.cars.iivmshome.sysmanage.model.AlarmInfoModel;

public interface AlarmInfoMapper {
	
	BaseCountsVo selectTotals(Map param);
	
	List<AlarmInfoModel> selectAll(Map param);
	
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_info
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    int insert(AlarmInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_info
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    int insertSelective(AlarmInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_info
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    AlarmInfoModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_info
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    int updateByPrimaryKeySelective(AlarmInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_info
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    int updateByPrimaryKey(AlarmInfoModel record);
}