package com.cars.iivmshome.sysmanage.dao;

import java.util.List;
import java.util.Map;

import com.cars.iivmshome.sysmanage.model.CameraInfoModel;

public interface CameraInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    int insert(CameraInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    int insertSelective(CameraInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    CameraInfoModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    int updateByPrimaryKeySelective(CameraInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table camera_info
     *
     * @mbggenerated Sat Oct 14 01:31:26 CST 2017
     */
    int updateByPrimaryKey(CameraInfoModel record);
    
    List<CameraInfoModel> selectByPid(Integer pid);
    
    int isValidByIP(Map<String, Object> map);
    
}