package com.cars.iivmshome.auth.vo;

import java.io.Serializable;

/**
 * 
 * @ClassName: DepartmentModel
 * @Description:部门持久化类
 * @author: jiangcy
 * @date: 2015年4月5日 下午8:24:35
 */
public class DepartmentInfoVo  implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1919589618134425332L;
	
	private Integer depId;
	private Integer parentDepId;

	private String depName;

	private Boolean isleaf;

	private String detail;

	private String domain;

	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_department.dep_id
	 *
	 * @return the value of security_department.dep_id
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public Integer getDepId() {
		return depId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_department.dep_id
	 *
	 * @param depId
	 *            the value for security_department.dep_id
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_department.parent_dep_id
	 *
	 * @return the value of security_department.parent_dep_id
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public Integer getParentDepId() {
		return parentDepId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_department.parent_dep_id
	 *
	 * @param parentDepId
	 *            the value for security_department.parent_dep_id
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public void setParentDepId(Integer parentDepId) {
		this.parentDepId = parentDepId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_department.dep_name
	 *
	 * @return the value of security_department.dep_name
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public String getDepName() {
		return depName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_department.dep_name
	 *
	 * @param depName
	 *            the value for security_department.dep_name
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public void setDepName(String depName) {
		this.depName = depName == null ? null : depName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_department.isleaf
	 *
	 * @return the value of security_department.isleaf
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public Boolean getIsleaf() {
		return isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_department.isleaf
	 *
	 * @param isleaf
	 *            the value for security_department.isleaf
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public void setIsleaf(Boolean isleaf) {
		this.isleaf = isleaf;
	}

	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_department.detail
	 *
	 * @param detail
	 *            the value for security_department.detail
	 *
	 * @mbggenerated Sun Apr 05 20:20:47 CST 2015
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}
}