package com.cars.iivmshome.auth.vo;

import java.io.Serializable;

/**
 * 
 * @ClassName: ModuleModel
 * @Description:模块持久化类
 * @author: jiangcy
 * @date: 2015年4月20日 下午5:24:42
 */
public class ModuleInfoVo  implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7504212282460444980L;

	private Integer moduleId;

	private String moduleCode;

	private String moduleName;

	private Integer priority;

	private Integer parentModuleId;

	private Boolean isshow;

	private String moduleIcon;

	private String moduleUrl;

	private Boolean isleaf;

	public Integer getModuleId() {
		return moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public String getModuleCode() {
		return moduleCode;
	}

	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode == null ? null : moduleCode.trim();
	}

	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName == null ? null : moduleName.trim();
	}

	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getParentModuleId() {
		return parentModuleId;
	}

	public void setParentModuleId(Integer parentModuleId) {
		this.parentModuleId = parentModuleId;
	}

	public Boolean getIsshow() {
		return isshow;
	}

	public void setIsshow(Boolean isshow) {
		this.isshow = isshow;
	}

	public String getModuleIcon() {
		return moduleIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_module.module_icon
	 *
	 * @param moduleIcon
	 *            the value for security_module.module_icon
	 *
	 * @mbggenerated Mon Apr 20 17:24:04 CST 2015
	 */
	public void setModuleIcon(String moduleIcon) {
		this.moduleIcon = moduleIcon == null ? null : moduleIcon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_module.module_url
	 *
	 * @return the value of security_module.module_url
	 *
	 * @mbggenerated Mon Apr 20 17:24:04 CST 2015
	 */
	public String getModuleUrl() {
		return moduleUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_module.module_url
	 *
	 * @param moduleUrl
	 *            the value for security_module.module_url
	 *
	 * @mbggenerated Mon Apr 20 17:24:04 CST 2015
	 */
	public void setModuleUrl(String moduleUrl) {
		this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column security_module.isleaf
	 *
	 * @return the value of security_module.isleaf
	 *
	 * @mbggenerated Mon Apr 20 17:24:04 CST 2015
	 */
	public Boolean getIsleaf() {
		return isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column security_module.isleaf
	 *
	 * @param isleaf
	 *            the value for security_module.isleaf
	 *
	 * @mbggenerated Mon Apr 20 17:24:04 CST 2015
	 */
	public void setIsleaf(Boolean isleaf) {
		this.isleaf = isleaf;
	}
}