package com.cars.iivmshome.auth.model;

public class AuthGroupModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.id
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.group_name
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.pid
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_group.group_mail
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    private String groupMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.id
     *
     * @return the value of auth_group.id
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.id
     *
     * @param id the value for auth_group.id
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.group_name
     *
     * @return the value of auth_group.group_name
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.group_name
     *
     * @param groupName the value for auth_group.group_name
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.pid
     *
     * @return the value of auth_group.pid
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.pid
     *
     * @param pid the value for auth_group.pid
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_group.group_mail
     *
     * @return the value of auth_group.group_mail
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public String getGroupMail() {
        return groupMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_group.group_mail
     *
     * @param groupMail the value for auth_group.group_mail
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    public void setGroupMail(String groupMail) {
        this.groupMail = groupMail == null ? null : groupMail.trim();
    }
}