package com.cars.iivmshome.auth.model;

public class AuthUserModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.account
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.password
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.group_id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.phone
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.real_name
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.id
     *
     * @return the value of auth_user.id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.id
     *
     * @param id the value for auth_user.id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.account
     *
     * @return the value of auth_user.account
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.account
     *
     * @param account the value for auth_user.account
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.password
     *
     * @return the value of auth_user.password
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.password
     *
     * @param password the value for auth_user.password
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.group_id
     *
     * @return the value of auth_user.group_id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.group_id
     *
     * @param groupId the value for auth_user.group_id
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.phone
     *
     * @return the value of auth_user.phone
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.phone
     *
     * @param phone the value for auth_user.phone
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.real_name
     *
     * @return the value of auth_user.real_name
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.real_name
     *
     * @param realName the value for auth_user.real_name
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}