package com.cars.iivmshome.auth.dao;

import com.cars.iivmshome.auth.model.AuthGroupModel;

public interface AuthGroupModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    int insert(AuthGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    int insertSelective(AuthGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    AuthGroupModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    int updateByPrimaryKeySelective(AuthGroupModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group
     *
     * @mbggenerated Tue Jul 18 21:36:50 CST 2017
     */
    int updateByPrimaryKey(AuthGroupModel record);
}