package com.cars.iivmshome.auth.dao;

import com.cars.iivmshome.auth.model.AuthUserModel;

public interface AuthUserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    int insert(AuthUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    int insertSelective(AuthUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    AuthUserModel selectByPrimaryKey(Integer id);

    AuthUserModel selectUserByUserName(String name);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    int updateByPrimaryKeySelective(AuthUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbggenerated Tue Jul 18 21:33:22 CST 2017
     */
    int updateByPrimaryKey(AuthUserModel record);
}