package com.cars.iivmshome.sysmanage.model;

public class AlarmTypeModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_type.type
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_type.id
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_type.name
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_type.type
     *
     * @return the value of alarm_type.type
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_type.type
     *
     * @param type the value for alarm_type.type
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_type.id
     *
     * @return the value of alarm_type.id
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_type.id
     *
     * @param id the value for alarm_type.id
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_type.name
     *
     * @return the value of alarm_type.name
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_type.name
     *
     * @param name the value for alarm_type.name
     *
     * @mbggenerated Sun Oct 29 11:12:39 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}