package com.cars.iivmshome.sysmanage.model;

public class CameraLocationInfoModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_location_info.id
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_location_info.name
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera_location_info.pid
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_location_info.id
     *
     * @return the value of camera_location_info.id
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_location_info.id
     *
     * @param id the value for camera_location_info.id
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_location_info.name
     *
     * @return the value of camera_location_info.name
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_location_info.name
     *
     * @param name the value for camera_location_info.name
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera_location_info.pid
     *
     * @return the value of camera_location_info.pid
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera_location_info.pid
     *
     * @param pid the value for camera_location_info.pid
     *
     * @mbggenerated Sat Oct 14 01:34:17 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}